### ISSUE TITLE
Not working in debug output

### ISSUE THREAD

**Issue by ajhalls** [AlexGhiondea/OutputColorizer#10]
Is this supposed to work in debug output? I was looking for a way to colorize my output to make debugging quicker but it doesn't appear to do anything.

**Comment by AlexGhiondea** [comment]
@ajhalls sorry for the late reply -- for some reason I am not getting notifications for my repos.

Are you asking if this will show up in the Output Window of Visual Studio? Or if this will work in a Debug build?
