### ISSUE TITLE
Consider using '[[' to escape '['

### ISSUE THREAD

**Issue by AlexGhiondea** [AlexGhiondea/OutputColorizer#5]
That would closer match how '{' is escaped.

**Comment by joperezr** [comment]
How are you escaping it today?

**Comment by AlexGhiondea** [comment]
Today you escape it using `\`. 
But you would need to write it like this: `\\[`, because `\` itself needs to be escaped.
If I use `[` and `]` then you would write this: `[[`

And this ambiguity: `"[[[Green!foo]]]"` can be resolved like this:
- for `[` the last one you find is the beginning of the color segment,
- for `]` the first one you find is the ending of the color segment

**Comment by AlexGhiondea** [comment]
Actually, you cannot resolve the ambiguity for the closing bracket. If you have nested entries, you cannot decide if ]] means escaping or if it means closing 2 segments.

Escaping { does not have this problem because they can never nest so }} is always the escaped value.
